[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
